apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ikusi
data:
  LOG_LEVEL: "INFO"
  UVICORN_WORKERS: "2"
  USERS_SERVICE_URL: "http://usuarios-service.ikusi.svc.cluster.local:8000"