name: Release Helm Chart

on:
  push:
    branches:
      - main   # o la rama que uses para desarrollo

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm Chart
        run: |
          cd charts/backend
          helm package .
          mv *.tgz ../../

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy chart and generate index
        run: |
          cp *.tgz gh-pages/
          cd gh-pages
          helm repo index . --url https://kyodevcorp.github.io/ikusi-bk-chart

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          publish_branch: gh-pages
          force_orphan: true